"""added column to record screenshots

Revision ID: 74d697bb9136
Revises: c173bef7c57b
Create Date: 2021-12-07 18:38:14.542428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d697bb9136'
down_revision = 'c173bef7c57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_data', sa.Column('farm_screenshot', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_data', 'farm_screenshot')
    # ### end Alembic commands ###
