"""added table to track coins

Revision ID: 8cf043086f2d
Revises: 68546f25bfa6
Create Date: 2021-12-04 23:04:45.788548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf043086f2d'
down_revision = '68546f25bfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_data')
    # ### end Alembic commands ###
