"""added datetime game data

Revision ID: c173bef7c57b
Revises: 8cf043086f2d
Create Date: 2021-12-06 17:44:31.669867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c173bef7c57b'
down_revision = '8cf043086f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_data', sa.Column('product_last_collected', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_data', 'product_last_collected')
    # ### end Alembic commands ###
